### ISSUE TITLE
Error report not begin generated

### ISSUE THREAD

**Issue by c-martinez** [lycheeverse/lychee-action#1]
In `entrypoint.sh`

https://github.com/lycheeverse/lychee-action/blob/b9d270dc4788c849d00b9647f93bb3bd2f9066ed/entrypoint.sh#L2

I think the `-e` option causes the script to end as soon as an error is encountered. This will mean that the if statement below is never reached.

https://github.com/lycheeverse/lychee-action/blob/b9d270dc4788c849d00b9647f93bb3bd2f9066ed/entrypoint.sh#L15-L19

And unfortunately that means the `$LYCHEE_OUT` report is never created. 

Is this correct?

One alternative would be to change `set -euxo pipefail` to `set -uxo pipefail`

Alternatively, lychee could be executed as `lychee "$@" --output "$LYCHEE_OUT"` (and then the `$LYCHEE_OUT` file be removed if not needed.

**Comment by mre** [comment]
Thanks! Just saw your issue. Help is on the way. I merged https://github.com/lycheeverse/lychee-action/commit/5abbdadaddae26c045f74832c946901b30d8566f, which should fix it. Can you try again and see if it fixes the problem?

**Comment by c-martinez** [comment]
Great, good to see this being fixed.

I'm not an expect with github actions -- do I need to somehow indicate I want to use the latest release of this action? `uses: lycheeverse/lychee-action@v1.0.1` or something like that?

**Comment by mre** [comment]
Yeah you can use the newly created tag now:

```
- name: lychee link checker action
  uses: lycheeverse/lychee-action@v1.0.4
```

I guess you could also use `master` to always get the latest version:

```
- name: lychee link checker action
  uses: lycheeverse/lychee-action@master
```

**Comment by c-martinez** [comment]
Yes, indeed, that works. Thanks!
