### ISSUE TITLE
Print Markdown File Path in the Console

### ISSUE THREAD

**Issue by joesan** [lycheeverse/lychee-action#11]
Is it possible to also print to the build console which file it being referenced?

Here is a snippet:

```
✅ https://ubuntu.com/tutorials/how-to-install-ubuntu-on-your-raspberry-pi#1-overview [200 OK]
✅ https://ubuntu.com/tutorials/install-the-arduino-ide#1-overview [200 OK]
🚫 https://navo-org.github.io//navo-docs/docs/tutorials/dc-motor-rpm.html#dc-motor-speed-control-arduino-sketch [404 Not Found]
🚫 https://en.wikipedia.org/wiki/PID_controller_test_ [404 Not Found]
```
Could the source Markdown file be printed along with this?

**Comment by mre** [comment]
That's more like a feature request for lychee. In fact is has been asked before. 😃 
https://github.com/lycheeverse/lychee/issues/114
It's on the todo list. Let's move the discussion over there.
