### ISSUE TITLE
Report in JSON Format Still Includes Markdown Link

### ISSUE THREAD

**Issue by aj-stein-nist** [lycheeverse/lychee-action#115]
Hello, already a big fan of this simple, elegant tool you wrote! I am working on using it to check our website content for a project. I noticed that, even when I pick format JSON, the file is inevitably a JSON file end with a Markdown link.

This is the result of the run from that action. I noticed prior to using GHA but here is an example.

https://github.com/aj-stein-nist/OSCAL/actions/runs/2301231596

[html_link_report.zip](https://github.com/lycheeverse/lychee/files/8662918/html_link_report.zip)

Is this intentional, can you/I/we consider generating the JSON without the additional non-JSON footer?

**Comment by mre** [comment]
Wow, apparently it checked 1400 links/second. Nice. 🤩
Moved the issue to lychee-action, no worries.

We have a check for that, but apparently it doesn't work:
https://github.com/lycheeverse/lychee-action/blob/c0d1093b783f7ad0c445884b01da0215b2da29ee/entrypoint.sh#L29-L30

Need to investigate a bit, but it's certainly a bug. Thanks for reporting.

**Comment by aj-stein-nist** [comment]
Awesome and timely, thanks @mre. Maybe this week I can try to fix the bug and contribute back. Sharing is caring afterall.

Thanks for the tool, big improvement over the alternatives. Looks like it is time to brush off my tabs to learn Rust and contribute back more than easier `bash` entrypoint fixes. 😅

**Comment by mre** [comment]
Version 1.5.0 with the fix was just released. ☺️
