### ISSUE TITLE
Unsupported `--include-verbatim` argument

### ISSUE THREAD

**Issue by StevenMaude** [lycheeverse/lychee-action#116]
I'm not entirely sure whether it's better to open the issue here or with lychee itself: it relates a little to the release process for both. But I encountered it here, so opening here.

From this repository's [README](https://github.com/lycheeverse/lychee-action/tree/c0d1093b783f7ad0c445884b01da0215b2da29ee#passing-arguments):

> See [lychee's documentation](https://github.com/lycheeverse/lychee) for all possible arguments.

As a user, I diligently read the docs and see `--include-verbatim` listed. On trying that flag:

> `error: Found argument '--include-verbatim' which wasn't expected, or isn't valid in this context`

and then get puzzled :thinking:

Then I realise it's [because `--include-verbatim` was added](https://github.com/lycheeverse/lychee/pull/523) after the current latest versioned release of [lychee (0.9.0)](https://github.com/lycheeverse/lychee/releases/tag/v0.9.0). And [this action uses the 0.9.0 release](https://github.com/lycheeverse/lychee-action/commit/bdf20d7677293464ea17227fd79618ed780705e3).

This inconsistency would be fixed by a new release of lychee and then updating the image here.

***

(I'm trying lychee out for one or two projects and it looks really good, by the way; thanks! :heart:)

**Comment by mre** [comment]
You're right. I was waiting for https://github.com/lycheeverse/lychee-action/issues/115, but I guess it's fine if we just create a new release right away.

**Comment by mre** [comment]
Version 1.5.0 with lychee v0.10.0 was just released. ☺️
