### ISSUE TITLE
URLs in markdown code blocks being incorrectly checked

### ISSUE THREAD

**Issue by wolf99** [lycheeverse/lychee-action#117]
The PR https://github.com/lycheeverse/lychee/pull/523 seems to indicate that code blocks in markdown will be ignored.

However this is not happening when I add this action in a workflow here: https://github.com/GitCredentialManager/git-credential-manager/pull/700

For example the `localhost` or `contoso` links are reported as failures. Those examples use fenced code block, indent code block, and inline code markdown formatting. Per these examples:

````markdown
```
https://example.com
```

    https://example.com

`https://example.com`
````

Have I done something wrong?

**Comment by mre** [comment]
Code blocks only get excluded when setting the `--include-verbatim` flag You need to set that in the `args` of the lychee-action in your pipeline.
That's a new feature and I need to make a new lychee release first. Also see https://github.com/lycheeverse/lychee-action/issues/116.

**Comment by wolf99** [comment]
Oh, maybe I misunderstood the discussion on `--include-verbatim` in the other issues.

You're saying that including things verbatim actually then _excludes_ some things (such as code blocks)?
The documentation shows: ``Find links in verbatim sections like `pre`- and `code` blocks``, which is the opposite of what I would like (which is to ignore links in such sections).

I had thought this was already the default case as I have the action running correctly on another project which I _think_ does this this OK

**Comment by mre** [comment]
Sorry for the confusion, my bad. What I meant was that the newest version of lychee already excludes code blocks by default, so no need to do anything. 😅

**Comment by wolf99** [comment]
Thanks that's what I expected. 
However if you see the link for the ci run in my initial post, that is not happening; instead it is checking, and failing, on lots of example links within markdown code sections.

**Comment by mre** [comment]
The lychee version of lychee-action is not up to date. I need to release a new version first.
