### ISSUE TITLE
create-issue-from-file can't find the lychee output

### ISSUE THREAD

**Issue by seisman** [lycheeverse/lychee-action#13]
I'm trying this action, but can't make it work. 

- Workflow file I'm using: https://github.com/GenericMappingTools/pygmt/pull/634/files
- One of the latest run: https://github.com/GenericMappingTools/pygmt/actions/runs/576905543

The action can correctly find broken links, and the results are saved in `/tmp/lychee/output.md`:

![image](https://user-images.githubusercontent.com/3974108/108300696-cc212e80-716e-11eb-964b-6963b5b106e1.png)

However, the create-issue-from-file action can't find the `/tmp/lychee/output.md`:

![image](https://user-images.githubusercontent.com/3974108/108300735-e0fdc200-716e-11eb-96e8-65a186b14a90.png)

![image](https://user-images.githubusercontent.com/3974108/108300780-f70b8280-716e-11eb-8065-d537d042bffd.png)

**Comment by mre** [comment]
I don't see any mistake with your config. Very confuseing. 🤔

**Comment by mre** [comment]
For reference, this is how it should look like: https://github.com/analysis-tools-dev/static-analysis/issues/651
Here's the config: https://github.com/analysis-tools-dev/static-analysis/blob/master/.github/workflows/links.yml
Do you see any differences?

**Comment by seisman** [comment]
I used `/tmp/lychee/out.md` in the "create-issue-from-file" action. Changing it to `./lychee/out.md` now works (https://github.com/GenericMappingTools/pygmt/issues/927). 

Sorry for the noise.

**Comment by mre** [comment]
Yay! Thanks for the feedback and for using lychee. 😃
