### ISSUE TITLE
Failed: Network error

### ISSUE THREAD

**Issue by JPHaus** [lycheeverse/lychee-action#132]
Lychee keeps finding one link with the "Failed: Network error" but the link seems to work fine. If it persists I can just ignore it but I figured I'd share it here too.

Example action run:
https://github.com/data-engineering-community/data-engineering-wiki/actions/runs/2458257021

Link that it fails on:
https://docs.riak.com/riak/kv/latest/

**Comment by mre** [comment]
The error I can see in your example run is actually for http://docs.basho.com/riak/kv/, which gets forwarded to https://docs.riak.com/riak/kv/latest/ when opened in a browser.

The logs say
> ✗ [ERR] http://docs.basho.com/riak/kv/ | Network error: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1921: (unable to get local issuer certificate)
Seems to be a certificate issue. Probably on their end. 

It works locally:

```
echo 'http://docs.basho.com/riak/kv/' | lychee - --verbose
✔ [200] http://docs.basho.com/riak/kv/

🔍 1 Total ✅ 1 OK 🚫 0 Errors
```

but not with HTTPS. I get a better error message, though:

```
echo 'https://docs.basho.com/riak/kv/' | lychee - --verbose
✗ [ERR] https://docs.basho.com/riak/kv/ | Network error: The certificate was not trusted.

Issues found in 1 input. Find details below.

[stdin]:
✗ [ERR] https://docs.basho.com/riak/kv/ | Network error: The certificate was not trusted.

🔍 1 Total ✅ 0 OK 🚫 1 Error (HTTP:1)
```

It works if you allow insecure connections:

```
echo 'https://docs.basho.com/riak/kv/' | lychee - --verbose --insecure                                                                                            ✘
✔ [200] https://docs.basho.com/riak/kv/

🔍 1 Total ✅ 1 OK 🚫 0 Errors
```

I'd say either exclude the domain from checking or set `--insecure`, which I would not recommend.
