### ISSUE TITLE
Fail PRs on links that became broken, but create issues for external links that just started breaking?

### ISSUE THREAD

**Issue by untitaker** [lycheeverse/lychee-action#134]
Is there an obvious recommended way to report issues for any link that became broken over time, and fail the PR for any introduced links that are immediately broken?

I want to specifically block any PRs that introduce broken links (mostly internal but doesn't have to be), and at the same time not break the master build if a website becomes unavailable.

**Comment by mre** [comment]
Not that I know of. https://github.com/lycheeverse/lychee-action/issues/17 is at least related. If we introduce an argument for only checking changes, we might as well be able to add one for new files.

**Comment by mre** [comment]
Once we got that functionality you could have two runs: one for new links with `fail: true` and one for existing ones with `fail: false `.

**Comment by asmeurer** [comment]
Is it possible to use the cache feature to require a pre-existing link to be broken for, say, 3 days in a row before reporting it as a failure? That way if a site just goes down for a little bit or just has an intermittent 503 it doesn't cause the link checker to fail.

**Comment by mre** [comment]
The cache file is to avoid repeated checks. For example, if the cache is valid for 24h and you run lychee multiple times within that time it would not check a link but immediately return the cached result. In that sense it's the opposite of what you want.

Instead, you could run lychee without a cache and store the _output_ in a file, which you can _then_ cache on Github. On the next run you would download that file again and compare the contents with the latest run to determine which links are broken for longer. This would require some manual scripting work.

**Comment by mre** [comment]
Thank you all for the valuable input on this topic. After reviewing the discussion, it's clear that the core challenge here revolves around managing broken links in PRs and the `master` build. The conversation has touched on several ideas, including:

* Blocking PRs with newly introduced broken links, as initially proposed by @untitaker.
* The possibility of using lychee's cache functionality to avoid repeated checks.
* Suggestions by @polarathene on handling links in PR diffs and scheduled checks for the production branch, which offer a good balance between thoroughness and efficiency.

However, it's important to note that the implementation of some of these suggestions extends beyond the current scope of the lychee-action. Specifically, the idea of requiring a link to be broken for a certain duration before reporting it as a failure, while interesting, involves a level of complexity and manual scripting that is currently out of scope.

As a workaround, I recommend considering the approach of having two separate runs for link checking: one for new links with `fail: true` and one for existing links with `fail: false`. This method would effectively address the immediate concern of blocking PRs with newly introduced broken links, while not breaking the `master` build if a website becomes unavailable.

Focusing on a workaround seems the best course of action.
