### ISSUE TITLE
How to ignore file:/// paths?

### ISSUE THREAD

**Issue by wolf99** [lycheeverse/lychee-action#136]
Hi

I am trying to add this action on the https://github.com/GitCredentialManager/git-credential-manager project.
The project includes some HTML files that are auto-generated by build tools that contain references to the local filesystem using paths like `file:///...`.

Of course these links fail for the link checker.
On https://github.com/GitCredentialManager/git-credential-manager/pull/700 see the "Lint documentation / Check for broken links (pull_request)" job.

I have tried using `--exclude-path "file:///"` (See https://github.com/GitCredentialManager/git-credential-manager/pull/700/commits/7304c593522d5fb70b63d846178815399bb3588a) but it has not had the desired affect - probably I am not using it correctly.
How can I tell Lychee to ignore such paths without ignoring the whole file?

Thanks!

**Comment by wolf99** [comment]
I think I misunderstood the purpose of the `--exclude-path` argument; it is for the setting of files within the repo that should not be checked rather than setting a path link within any file that it should ignore.

Instead I have tried adding a `.lycheeignore` file with the regex `file:\/\/\/.*
 (https://github.com/GitCredentialManager/git-credential-manager/pull/700/commits/3a8767caf7c8419717693acc355e29d5447175ae)

**Comment by mre** [comment]
Alternatively `lychee --scheme http https -- example.com`.
