### ISSUE TITLE
Markdown output less helpful than it used to be

### ISSUE THREAD

**Issue by buddhist-uni** [lycheeverse/lychee-action#148]
Back in `v1.0.8`, the markdown output would include the HTTP code and description of the problem for broken links:

```
✗ [503] http://monastic-asia.wikidot.com/ | Network error: Service Unavailable
⧖ [TIMEOUT] http://www.ahandfulofleaves.org/ | Timeout
✗ [404] https://journals.equinoxpub.com/article/view/19524 | Network error: Not Found
✗ [403] https://www.researchgate.net/some.pdf | Network error: Forbidden
```

This was extremely helpful for me in identifying which errors were likely genuine (e.g. 404, 503...) and which likely transitory (e.g. 403, TIMEOUT, etc).

The new markdown output just says `Failed: Network error` for everything, which is less helpful.

**Comment by mre** [comment]
Yes, this is a regression from refactoring and will be fixed with the next lychee release (0.10.1).
See https://github.com/lycheeverse/lychee/issues/672.

**Comment by mre** [comment]
Should be fixed in `master` now.

**Comment by mre** [comment]
A fix was released in v1.5.1. @buddhist-uni can you report back if that resolved the problem so that I can close this issue? 🙏

**Comment by buddhist-uni** [comment]
They now say, e.g.,

`Failed: Network error (status code: 503)`

which is good enough for me _most_ of the time, but without the description I may have to Google the status code if something rare like a `425` comes up. 🤷

**Comment by mre** [comment]
You are right. We should add back that information.

**Comment by tooomm** [comment]
I mentioned this in https://github.com/lycheeverse/lychee/issues/694 as well.
>The `Network error: Not Found` gives more information vs. `Failed: Network error` as well and explains the code a bit better.

**Comment by mre** [comment]
@buddhist-uni @tooomm, I created https://github.com/lycheeverse/lychee/pull/729 if you want to check the output and tell me if it looks good to you.

**Comment by mre** [comment]
I expect this to be resolved with the latest updates. Feel free to reopen if this is not the case.
