### ISSUE TITLE
The default arguments aren't sorted right?

### ISSUE THREAD

**Issue by laralove143** [lycheeverse/lychee-action#161]
My action file includes
```yaml
- name: Check Links
  uses: lycheeverse/lychee-action@v1
  with:
    fail: true
    args: "--verbose --no-progress --exclude 'https://github.com/gaybreak/*' './README.md' './src/**/*'"
```
which follows the [defaults](https://github.com/lycheeverse/lychee-action/blob/master/action.yml), but it returns
```
++ lychee --format markdown --output /tmp/lychee/out.md --verbose --no-progress --exclude 'https://github.com/gaybreak/*' ./README.md './src/**/*'
error: The following required arguments were not provided:
    <inputs>...
```
Running the same command locally returns the same error as well, won't this break the workflow entirely even with no args option because of the default?

**Comment by mre** [comment]
You need to add double dashes after the exclude, because it's an option which supports multiple arguments. ```--exclude ... --```
