### ISSUE TITLE
Problem setting max-redirect arg on action

### ISSUE THREAD

**Issue by SeanKilleen** [lycheeverse/lychee-action#164]
Maybe this is an upstream issue; let me know if it is.

## Summary

**Background:** I'm in the process of updating GitHub's Octokit.net codebase to use newer doc links. Currently, many of their links are 301 permanently redirected. 

**Goal:** I'd like to use the lychee-action to fail on links that are redirected.

**What I tried:** specifying `args: --max-redirects 0` in the GitHub Action YAML for the action. (tried with quotes as well)

**What I expected**: Many failed links due to lots of 301 redirects.

**What actually happened**: Looks like the action itself failed to run, noting that I had not specified `<inputs>`.

## Links

* In-progress PR where I'm making these docs changes and introducing lychee-action: https://github.com/octokit/octokit.net/pull/2571
* Commit I tried without quotes: https://github.com/octokit/octokit.net/pull/2571/commits/deb7d9827ac42a49325ff6bfd0f8c330e361c161
* Commit I tried with quotes: https://github.com/octokit/octokit.net/pull/2571/commits/024ea90db4b0375f22c6f5f2a5206dc6ff458641
* Example failure output: https://github.com/octokit/octokit.net/actions/runs/3061512478/jobs/4941369755

**Comment by mre** [comment]
This was resolved in https://github.com/lycheeverse/lychee/pull/987. In `lychee@master` the `max-redirect` flag gets properly reflected. The change will go live with the next release and will then be available in `lychee-action`.
Thanks for your patience.
Feel free to reopen in case it doesn't work with the next lychee-action release (>1.6.1).
