### ISSUE TITLE
Release new version (1.5.2?)

### ISSUE THREAD

**Issue by Kielek** [lycheeverse/lychee-action#168]
Could you please make a release/tag, Probably 1.5.2?

It will be great to remove warnings from the build pipeline. The issue was fixed in PR #167.

**Comment by mre** [comment]
Oh yeah, I should do that. After so many years I'm still pretty bad at this "release" thing. 😜

**Comment by vpereira01** [comment]
Related to release a new version you might want to make that new version is marked as the latest version.

Currently, if you check https://github.com/lycheeverse/lychee-action/releases you see that https://github.com/lycheeverse/lychee-action/releases is marked as latest.

I think this also affects how information is shown on the marketplace, there v1 is also the latest version.

**Comment by mre** [comment]
1.5.2 is out.
@vpereira01 made sure that the latest version shows up on the Marketplace again. Thanks for the hint. 👍
