### ISSUE TITLE
Releases have same SHA?

### ISSUE THREAD

**Issue by wolf99** [lycheeverse/lychee-action#169]
On https://github.com/lycheeverse/lychee-action/releases

![image](https://user-images.githubusercontent.com/281700/199845213-a60475dc-4d66-4764-a2b5-ed7c1d40a58c.png)

![image](https://user-images.githubusercontent.com/281700/199845266-152e6724-49e2-43ec-8572-74b5f5564878.png)

Is something gone wrong?

**Comment by mre** [comment]
That's on purpose. `v1` always points to the latest released sha. The idea is that people can just use `v1` and it will point to the latest 1.x version as per semver. Does that answer your question or do you face an issue? 🤔

**Comment by mre** [comment]
Thanks for keeping an eye out, though. Appreciate it. 🤗

**Comment by tooomm** [comment]
@mre `v1` hasn't been updated, and I missed the last 3 releases.

`Download action repository 'lycheeverse/lychee-action@v1' (SHA:0fcec0b45a1cc548fd8b6d9e859b1f8a2cc156ce)`

**Comment by mre** [comment]
I'm sorry for this. Will fix asap.
Ideally I'd find a way to automate tagging the release because there's a high chance I'll forget again in the future.

**Comment by tooomm** [comment]
>Ideally I'd find a way to automate tagging the release because there's a high chance I'll forget again in the future.

Could a GitHub Action workflow that runs on tags or releases and runs a little script with the needed commands work?

**Comment by mre** [comment]
Maybe something like this could work: https://github.com/Actions-R-Us/actions-tagger
I'd appreciate some feedback and maybe a pull request to add the action.

**Comment by mre** [comment]
Just released 1.7.0 and v1 was automatically updated.
Logs here: https://github.com/lycheeverse/lychee-action/actions/runs/4726601856/jobs/8386343900
Nice work!
