### ISSUE TITLE
Errors in output from entrypoint.sh

### ISSUE THREAD

**Issue by wolf99** [lycheeverse/lychee-action#170]
I can see the following from Bash in the output from the action:

```console
mkdir: cannot create directory ‘lychee’: File exists
/home/runner/work/_actions/lycheeverse/lychee-action/25f59e1bc8f12b314a1e[36](https://github.com/exercism/problem-specifications/actions/runs/3396200796/jobs/5646999010#step:3:39)6f825e00d13de2d80b/entrypoint.sh: line 33: lychee/out.md: Not a directory
/home/runner/work/_actions/lycheeverse/lychee-action/25f59e1bc8f12b314a1e366f825e00d13de2d80b/entrypoint.sh: line 36: lychee/out.md: Not a directory
```

A run where this happens: https://github.com/exercism/problem-specifications/actions/runs/3396200796/jobs/5646999010

The referenced file is the action [entrypoint.sh](https://github.com/lycheeverse/lychee-action/blob/master/entrypoint.sh).

I tried playing around with similar commands in my Bash shell (below) but everything worked fine there, so this may be something specific to running in a container and the file system present (or not present) there 🤷 .

My quick local test of the related Bash commands.
One thing different here that is shown in the error output above, is the workflow URL does not get the ID of course, so perhaps there is some issue there?

```console
~/test❯ LYCHEE_TMP="tmp/lychee/out.md"
~/test❯ INPUT_OUTPUT="lychee/out.md"
~/test❯ GITHUB_WORKFLOW_URL="https://github.com/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}?check_suite_focus=true"

~/test❯ mkdir -p "$(dirname $LYCHEE_TMP)"
~/test❯ echo $?
0

~/test❯ mkdir -p "$(dirname -- "${INPUT_OUTPUT}")"
~/test❯ echo $?
0

~/test❯ cat "${LYCHEE_TMP}" > "${INPUT_OUTPUT}"
~/test❯ echo $?
0

~/test❯ echo "[Full Github Actions output](${GITHUB_WORKFLOW_URL})" >> "${INPUT_OUTPUT}"
~/test❯ cat lychee/out.md
[Full Github Actions output](https://github.com//actions/runs/?check_suite_focus=true)
```

**Comment by mre** [comment]
Fixed that in `master`. Will go live with the next release.

**Comment by mre** [comment]
https://github.com/lycheeverse/lychee-action/pull/172

**Comment by mre** [comment]
Closing this as (hopefully) resolved. 😊
