### ISSUE TITLE
Issue in version 1.5.4 with links to Twitter

### ISSUE THREAD

**Issue by lechnerc77** [lycheeverse/lychee-action#178]
## Issue

I am facing an issue with version [1.5.4](https://github.com/lycheeverse/lychee-action/releases/tag/v1.5.4) of the GitHub Action, when it comes to checking links on Twitter. All links to Twitter are timing out although being reachable e.g. via `curl` without any timing issues.

## Preliminary Analysis
I checked the 1.5 release line and the checks work fine until release [1.5.3](https://github.com/lycheeverse/lychee-action/releases/tag/v1.5.3).

I prepared a sample repo and executed GH Action runs with version 1.5.0 until 1.5.4. The runs is available [here](https://github.com/lechnerc77/test-lychee-twitter/actions/workflows/linkswatcher.yml). 

## Additional Information

The main repo where I got aware of the issue is [https://github.com/marcduiker/azure-functions-university](https://github.com/marcduiker/azure-functions-university). A run showing the time outs is available [here](https://github.com/marcduiker/azure-functions-university/actions/runs/3859458099). 

## Workaround

The workaround is to downgrade from version 1.5.4 to 1.5.3

**Comment by lechnerc77** [comment]
Retried it and now it works with version 1.5.4 - it must be something wrt to networking between the GH Action runner and Twitter. At least I have no other explanation for this. I close the issue as probably no relation to the Action or lychee

**Comment by mre** [comment]
Thanks for reaching out.

Twitter does not return plain HTML responses (not even to Googlebot) and requires JavaScript and an authenticated API call. Therefore we can't check Twitter links directly. Instead we redirect twitter links to nitter.net, which is a free and open source alternative Twitter front-end which [does not require executing JavaScript](https://nitter.net/about) or authentication. It's not perfect, but it's better than nothing.

Recently I learned that Nitter is struggling with [bot attacks that trigger rate-limiting](https://github.com/zedeus/nitter/issues/740), thus causing some tweets to be unavailable. (In fact all tweets are unavailable except pinned tweets.) I have not heard of entire Twitter being down yet, though.)
Some more examples are https://github.com/zedeus/nitter/issues/374, https://github.com/zedeus/nitter/issues/707 and https://github.com/zedeus/nitter/issues/745. That said, I don't know of a better alternative to checking Twitter links.

**Comment by lechnerc77** [comment]
@mre Thanks for the detailed description of the flow. That helps a lot in understanding what's happening "behind the scenes".

We will monitor the issue with Twitter and in case exclude the links from the check
