### ISSUE TITLE
Typos in README

### ISSUE THREAD

**Issue by phieri** [lycheeverse/lychee-action#182]
On three occations in the README there's an extra v character:
- https://github.com/lycheeverse/lychee-action/blob/9ace499fe66cee282a29eaa628fdac2c72fa087f/README.md?plain=1#L73
- https://github.com/lycheeverse/lychee-action/blob/9ace499fe66cee282a29eaa628fdac2c72fa087f/README.md?plain=1#L103
- https://github.com/lycheeverse/lychee-action/blob/9ace499fe66cee282a29eaa628fdac2c72fa087f/README.md?plain=1#L128

**Comment by mre** [comment]
Oof. I messed up when I updated the version number. Would you like to create a pull request to fix it?
