### ISSUE TITLE
Solution for "Error: Resource not accessible by integration"

### ISSUE THREAD

**Issue by zcraber** [lycheeverse/lychee-action#194]
### This is not a bug report.

Just sharing a solution, that worked for me. In case anyone gets the `Error: Resource not accessible by integration` while running the workflow, try this:

1. Go to your repository `Settings`.
2. Select `General` from `Actions`.
3. Under `Workflow permissions`, check `Read and write permissions`.

![image](https://github.com/lycheeverse/lychee-action/assets/61133303/d3118f76-1b45-45b6-8705-f56ec92b740b)

Previously, repositories had this setting enabled by default. Seems like this has been changed.

**Comment by zcraber** [comment]
> Huh, thanks for the heads-up. I wonder why write permissions are required by the action. We don't write anything except for the status report at the end of the run. We don't write anything to the repo itself. Anybody has an idea what's going on? We might need to add further instructions to the readme if this is a common problem.
> 
> I will reopen this issue as I'd like to get more feedback.

I guess it's related to https://github.com/peter-evans/create-issue-from-file

![image](https://github.com/lycheeverse/lychee-action/assets/61133303/1ab81e0b-5a0f-4c55-926a-da8285d318f7)

**Comment by mre** [comment]
Do you still encounter this problem? I can't see any issues in any of the other pipelines so far.

**Comment by zcraber** [comment]
> Do you still encounter this problem? I can't see any issues in any of the other pipelines so far.

Nope, it was solved when I enabled` Read and write permission`

**Comment by mre** [comment]
Alright. Thanks for the update. Closing then.

**Comment by AndreiCherniaev** [comment]
> > Do you still encounter this problem? I can't see any issues in any of the other pipelines so far.
> 
> Nope, it was solved when I enabled `Read and write permissions`

For me this also helps, great thanks! But why I can't read about this in readme.md? May be we should add such very important note:
_Before start edit settings of repo to enable "Read and write permissions"_
Screenshort:
![Read and write permissions](https://github.com/user-attachments/assets/e5b4b3ed-b366-469f-ae1b-87abc74fb3f4)

@mre @dscho @jacobdalamb

**Comment by dscho** [comment]
This makes lots of sense, and I agree that:

```
Error: Resource not accessible by integration
```

does not clearly say:

```
Error: This operation is using a token that is missing some scopes;
  You may want to add `issues: write`; For more information, see
  https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#permissions
```

So: an alternative to default workflow permissions to read/write, and an alternative that I would prefer, personally, would be to add this top-level section to the GitHub workflow definition:

```yml
permissions:
  issues: write
```

Or even better: scope it to the _job_ in the workflow that needs that permission:

```yml
jobs:
  my-job:
    permissions:
      issues: write
```

See [a working example](https://github.com/git-for-windows/git/blob/d1cf3f7b83c013380b679c3bb9c24f2f05378ce4/.github/workflows/monitor-components.yml#L22-L23) that can be imitated.

> how user of `lychee-action` can know?

That's a good point, if you follow the example in the `README.md`, you wouldn't know. It would probably make for a fine contribution to add that `permissions` block with a comment along the lines `# needed for create-issue-from-file to work` [here](https://github.com/lycheeverse/lychee-action/blob/c38ba4f281730ee0d64e6963f49b708e01567b86/README.md?plain=1#L29) and [here](https://github.com/lycheeverse/lychee-action/blob/c38ba4f281730ee0d64e6963f49b708e01567b86/.github/workflows/links.yml#L11). @AndreiCherniaev wanna grab this opportunity to add a notch on your PR belt?

**Comment by mre** [comment]
@AndreiCherniaev, are you interested in sending a pull request?

**Comment by AndreiCherniaev** [comment]
> @AndreiCherniaev, are you interested in sending a pull request?

I don't have time in these two months. If someone else can do I will be happy.

**Comment by mre** [comment]
All good. It's up for grabs, then.
