### ISSUE TITLE
How to use exclude args

### ISSUE THREAD

**Issue by Wuliyuanulb** [lycheeverse/lychee-action#2]
Hi,

I saw Lychee support exclude args, I tried using this action, but it seems like it doesn't work. So is it support exclude?

Thanks

**Comment by gkellogg** [comment]
I got it to work to exclude example.org with the following:

    - name: Link Checker
      uses: lycheeverse/lychee-action@v1
      with:
        args: -v index.html --exclude http://example.org/

**Comment by Wuliyuanulb** [comment]
@gkellogg Thanks a lot :). And by the way, do you know how to let lychee check all files under one folder, even under sub-folders. I asked them just now, but they haven't reply to me.

**Comment by gkellogg** [comment]
> @gkellogg Thanks a lot :). And by the way, do you know how to let lychee check all files under one folder, even under sub-folders. I asked them just now, but they haven't reply to me.

According to the help for lychee, `--include` takes a regular expression, so maybe try that.

I just [downloaded the lychee executable](https://github.com/lycheeverse/lychee/releases) and worked on it locally to figure out the proper options to use.

**Comment by mre** [comment]
ℹ️ The solution is here: https://github.com/lycheeverse/lychee/issues/112
