### ISSUE TITLE
feat: support using nightly version

### ISSUE THREAD

**Issue by kemingy** [lycheeverse/lychee-action#203]
As we accomplished in https://github.com/lycheeverse/lychee/pull/1212. We're now able to use the nightly release. However, I found that this action will add a `v` prefix to the `lycheeVersion`.

I'm not sure which way you prefer:
- remove the `v` prefix and set the default `lycheeVersion` to `v0.13.0`
  - this might break some users if they're using a specific version
- add a new argument

What do you think? I'm glad to create a PR.

**Comment by mre** [comment]
I would say the first option is the cleanest, as this is clearly a paper cut, which can trip people up.

In order to avoid breaking changes, let's prepare a PR which removes the `v` prefix and release a version 2 of the action along with https://github.com/lycheeverse/lychee-action/pull/86 and https://github.com/lycheeverse/lychee-action/pull/85. Sounds good?

**Comment by kemingy** [comment]
SGTM. Let me create PR for this.

**Comment by tooomm** [comment]
As it fits the idea...
Did you also consider to allow `lycheeVersion: latest` to grab not the nightly, but the latest full release.

Currently, this repo needs a manual push to match a new release on the main repo, e.g. https://github.com/lycheeverse/lychee-action/commit/5d778f12698c76948e17c76729f3222acf92594a.

**Comment by mre** [comment]
@kemingy, do you have any thoughts on this? I'm not sure what to do here. I wouldn't be against adding such an option, but it might be some additional work.

**Comment by kemingy** [comment]
I think it requires additional logic to get the latest release version in the [action](https://github.com/lycheeverse/lychee-action/blob/master/action.yml).

One possible cmd is:
```bash
gh release list --repo lycheeverse/lychee --exclude-drafts --exclude-pre-releases --limit 1 | awk '{print $4}'
```
