### ISSUE TITLE
Improved GHA workflow for centralising url status reporting in single GH issue

### ISSUE THREAD

**Issue by VeckoTheGecko** [lycheeverse/lychee-action#209]
I thought I would share my (imo) improved GHA workflow for link status reporting, which uses and updates a single dedicated issue opening and closing the issue depending on whether errors are reported. This allows parties to subscribe/unsubscribe to the issue, while also preventing pollution as a result of creating multiple new issues.

I personally prefer this workflow than the one in this repos README, feel free to take and adapt if you so wish.

Note this workflow doesn't work on forks.

https://gist.github.com/VeckoTheGecko/7b6bb062135e59fbc9c5703c48435f5f

**Comment by mre** [comment]
That's great!
Would you like to add it to the official lychee documentation [here](https://github.com/lycheeverse/lycheeverse.github.io)?

**Comment by mre** [comment]
There is already something similar, which might need updating: https://lychee.cli.rs/#/github_action_recipes/reuse-issue
The source code for that file is here: https://github.com/lycheeverse/lycheeverse.github.io/blob/master/github_action_recipes/reuse-issue.md

**Comment by mre** [comment]
@VeckoTheGecko, I just wanted to reach out and let you know that I’m still very interested in incorporating your contribution into the repository. If you find some time to create a pull request, please go ahead and submit it, and then drop a comment here. I'll make sure to reopen the issue right away.

For now, I'm going to close this issue to help keep our issue tracker organized and tidy. However, I really hope to see your contribution soon. Thanks for the interest.
