### ISSUE TITLE
The `set-output` command is deprecated 

### ISSUE THREAD

**Issue by tannerjones4075** [lycheeverse/lychee-action#213]
Running the lycheeverse/lychee-action@v1.0.8 and get the following output: 
![image](https://github.com/lycheeverse/lychee-action/assets/78619684/00424633-f063-48cb-a17e-de43b97d5e2a)

**Comment by tannerjones4075** [comment]
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by mre** [comment]
Yes, that would be amazing. 

The example in the link explains the transition really well. https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/#examples

You would need to replace all occurrences of set-output with the new syntax. A search for all occurrences should be enough to find the spots.

**Comment by tooomm** [comment]
https://github.com/lycheeverse/lychee-action/pull/167 replaced `set-output` with `$GITHUB_ENV` instead `$GITHUB_OUTPUT` over a year ago.

You are using a very old version (v1.0.8) @tannerjones4075

**Comment by mre** [comment]
Indeed. Sorry, I overlooked that. In the back of my mind I remembered that we did something along those lines, but I thought that maybe we forgot a spot. 😅 Guess we can close this.
