### ISSUE TITLE
link.yml does not appear under GitHub actions

### ISSUE THREAD

**Issue by lyashevska** [lycheeverse/lychee-action#231]
`links.yml` does not appear under GitHub actions.
See example [here](https://github.com/esciencecenter-digital-skills/workshop-metadata/blob/129-linkchecker-workflow/.github/workflows/links.yml)
Any help is appreciated.

**Comment by lyashevska** [comment]
Thanks, thats clear, is there any workflow for testing beforehand?

**Comment by mre** [comment]
This is more of a GitHub Actions question than a lychee-action issue, but you can find some details on how to test your workflow before merging here: https://stackoverflow.com/questions/67707244/how-to-test-github-workflow-without-merging-into-master-main-branch

I recommend adding

```yaml
on: workflow_dispatch
```

to your workflow. Then an admin get dispatch (trigger) the workflow manually from the `Actions` page.
Hope that helps.

**Comment by lyashevska** [comment]
Thanks, this is helpful.
