### ISSUE TITLE
`${{ steps.lychee.outputs.exit_code }}` is not set correctly

### ISSUE THREAD

**Issue by sebastiaanspeck** [lycheeverse/lychee-action#244]
According to https://github.com/lycheeverse/lychee-action/blob/5047c2a4052946424ce139fe111135f6d7c0fe0b/action.yml#L40-L43 `${{ steps.lychee.outputs.exit_code }}` should be set, but instead the exit_code is solely saved to an env [`lychee_exit_code`](https://github.com/lycheeverse/lychee-action/blob/5047c2a4052946424ce139fe111135f6d7c0fe0b/entrypoint.sh#L71).

IMO the quickest fix is to change it to:
```
echo "lychee_exit_code=$exit_code" >> $GITHUB_ENV
echo "exit_code=$exit_code" >> $GITHUB_OUTPUT
```

**Comment by mre** [comment]
Oh, that's bad. Would you mind opening a pull request to apply your suggested fix?
