### ISSUE TITLE
bug: `Remove the downloaded archive and any unnecessary files after installation`

### ISSUE THREAD

**Issue by meysam81** [lycheeverse/lychee-action#254]
This line right here:

https://github.com/lycheeverse/lychee-action/blob/731bf1a2affebd80fab6515ba61d2648a76929a4/action.yml#L102

... is removing the `lychee.toml` file and the end result is as you see below:

```
Cannot load configuration file `lychee.toml`: No such file or directory (os error 2)
```

<img width="978" alt="Screenshot 2024-10-10 at 11 21 58" src="https://github.com/user-attachments/assets/5b453a45-7585-4ff7-9139-5a7febfa5da2">

**Comment by mre** [comment]
This should be fixed in the latest version, as per https://github.com/lycheeverse/lychee-action/pull/255.
Thanks for reporting.
