### ISSUE TITLE
Feature Request: Add json output option

### ISSUE THREAD

**Issue by vncsna** [lycheeverse/lychee-action#35]
I would like to have an option to get the json report, and then further modify this output to generate a styled markdown comment. An example of such comment could be a markdown with links to the markdown files with errors.

**Comment by mre** [comment]
You can use `--format json` to change the output file format of the status report to JSON. Does that answer your question?

**Comment by vncsna** [comment]
If I add `-- format json` it will override the standard markdown output?

**Comment by mre** [comment]
Yup, it will use JSON instead. (Just fyi: there may be no extra space between `--` and `format`. Otherwise lychee treats `format` and `json` as input files and not as one argument. This is a [POSIX](https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap12.html#tag_12_02) standard.)

**Comment by vncsna** [comment]
Thanks

**Comment by micalevisk** [comment]
> You can use --format json to change the output file format 

this isn't true anymore

https://github.com/lycheeverse/lychee-action/blob/53aae90c425dd7e50ea3cda9b3e551be2cabfb08/entrypoint.sh#L12

When I ran `lychee --format markdown --format json` I got this error:

```
error: The argument '--format <format>' was provided more than once, but cannot be used multiple times

USAGE:
    lychee <inputs>... --config <config-file> --format <format> --max-concurrency <max-concurrency> --max-redirects <max-redirects> --method <method> --timeout <timeout> --user-agent <user-agent>

For more information try --help
```

![image](https://user-images.githubusercontent.com/13461315/144895876-9cb0d0d6-2eb5-4fc0-842b-a1bce1d32006.png)

---

I guess it would be cool if we have an optional `FORMAT` env. var. to define the value for `--format` option. Or maybe an input will be better, like:

```yaml
     - name: Link Checker
        uses: lycheeverse/lychee-action@v1.1.1
        with:
          args: --verbose --no-progress **/*.md **/*.html
          format: json
```

**Comment by mre** [comment]
Oh my. Sorry about that regression.
@micalevisk would be comfortable creating a PR for that? Otherwise I can also do it.

**Comment by micalevisk** [comment]
I did understand that something like

```bash
# ...
LYCHEE_FORMAT=${INPUT_FORMAT:="json"}

lychee --format "$LYCHEE_FORMAT" --output "$LYCHEE_TMP" "$@" 

# ...
```

would work. But I'm unsure on how could remove any ocurrence of `--format` option on that `"$@"` :/ so I can't create a PR

**Comment by micalevisk** [comment]
actually, I just figure this out. I'll create the PR.

**Comment by mre** [comment]
Don't think there's an elegant way.
Given that `--format` is a new flag I doubt that anyone overwrote it already.
But to be 100% sure we could introduce the `format` input behind a v2.

**Comment by mre** [comment]
Oh okay. 😆

**Comment by micalevisk** [comment]
so I'll fix that regression but detecting if `$@` has an occurrence of `--format`. Is this fine?

**Comment by mre** [comment]
Yeah that's fine. Thanks for the quick fix @micalevisk. 🥳
