### ISSUE TITLE
Update README example to use `peter-evans/create-issue-from-file@v3`

### ISSUE THREAD

**Issue by mx-psi** [lycheeverse/lychee-action#38]
The README example uses `peter-evans/create-issue-from-file@v2`, but a new version has been released. It would be awesome if the example was updated to work with the new Action version

**Comment by mre** [comment]
Sure, I've updated the docs to mention `peter-evans/create-issue-from-file@v3`. AFAICT the changes are pretty minimal from a user's perspective. Release notes here: https://github.com/peter-evans/create-issue-from-file/releases/tag/v3.0.0.
Let me know if I forgot anything and thanks for the heads up.
