### ISSUE TITLE
Exclude specific files from link checker

### ISSUE THREAD

**Issue by VachaShah** [lycheeverse/lychee-action#39]
Hi, I have a use case where I want to exclude specific files from being checked in the link checker. Currently my args are as below:

```
args: --accept=200,403,429 "**/*.html" "**/*.md" "**/*.txt" "**/*.json"
```

I want to exclude some type of text files like files with names containing a specific word example anything with word `file` in the name like `sample-file.txt`. Is there a way to achieve this?

Thank you!

**Comment by mre** [comment]
Hey Vacha,

thanks for trying lychee! 🌟 

I don't think that's easily possible at the moment. At least not within lychee itself.
You can try something like this maybe: https://github.com/lycheeverse/lychee/issues/284
The idea is to use `find` for that or delete the unnecessary files before calling lychee.

There is also an `--exclude` parameter, but it only excludes URLs within the documents.
That said, it would be nice to add excludes for files or glob patterns in lychee as well.
I could think of `--exclude file://path/to/sample-file.txt` or even `--exclude file://*file*`.
But the more generic solution would probably be to fix https://github.com/lycheeverse/lychee/issues/284 and add a `!` option so you could write 

```
args: --accept=200,403,429 "**/*.html" "**/*.md" "**/*.txt" "**/*.json" "!*file*"
```

I think we should move the discussion over to the main lychee repo, as this feature will need to be added to lychee itself. 😄
Will close this in favor of https://github.com/lycheeverse/lychee/issues/284.
