### ISSUE TITLE
Seems to be misparsing some links

### ISSUE THREAD

**Issue by shonfeder** [lycheeverse/lychee-action#5]
I am reporting this on the action rather than the main utility repo because I am only seeing this behavior in the action.

I am getting the following failure:

```
🚫 https://raw.githubusercontent.com/informalsystems/apalache/99e58d6f5eebcc41f432a126a13a5f8d2ae7afe6/logo-apalache.svg/ [400 Bad Request]
```

while trying to run on a markdown file that contains this block of inline HTML:

```html
<div align="center">
<img
src="https://raw.githubusercontent.com/informalsystems/apalache/99e58d6f5eebcc41f432a126a13a5f8d2ae7afe6/logo-apalache.svg"
alt="Apalache Logo">
```

`lychee` seems to be appending a `/` to the end of the link? You can see our failing CI step while trying to put this to use here: https://github.com/informalsystems/apalache/runs/1670269221?check_suite_focus=true#step:4:53

**Comment by mre** [comment]
Yup, that's a bug. 😅 
We use a [linkify](https://github.com/robinst/linkify) for detecting the links, so we'd have to check how they handle the parsing in that case.

**Comment by mre** [comment]
Err, no. It seems to be a bug with lychee. Ran some tests on linkify and they seem to work just fine.

**Comment by mre** [comment]
This works now with the latest version of lychee. @shonfeder I've tested it on your repo and it seems to be fine.
Just in case you wanna give it another try. 😅
