### ISSUE TITLE
"unable to get local issuer certificate"

### ISSUE THREAD

**Issue by bogosj** [lycheeverse/lychee-action#51]
I'm encountering some URLs where I get the following error:

https://www.mysuezwater.com/ (error sending request for url (https://www.mysuezwater.com/): error trying to connect: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:../ssl/statem/statem_clnt.c:1915: (unable to get local issuer certificate))

A quick check seems to show a valid cert when visiting that site in Chrome. Is this caused by the root certs that are available on the ubuntu-latest image?

**Comment by mre** [comment]
> It appears to be a GoDaddy parent cert causing the problem?

Yeah that seems to be the case. Don't think we can do much here at this point so I'm closing the issue. 😞 Please correct me if I'm mistaken, though.
