### ISSUE TITLE
Why Docker?

### ISSUE THREAD

**Issue by wolf99** [lycheeverse/lychee-action#52]
Using this action, I come to see that GitHub Docker actions are generally inefficient.
For e.g., if I understand correctly, it seems lake an intermediate container is created by GitHub for ever `LABEL` in the dockerfile  😬 

Is there a specific reason(s) that the action was created as a Docker action rather than a composite action?

Would be interested to try to help to convert to composite action if there are no specific reasons for being a  Docker action and there is no objection.

**Comment by wolf99** [comment]
Yeah, Docker generally builds in layers, but seems like GitHub is doing something a little different when building an action.
See an example here: https://github.com/exercism/c/runs/4097894299?check_suite_focus=true
Scroll up and expand the step for "Build  Lycheeverse/lychee-action@...

Docker starts by pulling layers as you have mentioned:

```console
  Step 1/12 : FROM lycheeverse/lychee:0.7.1@sha256:ff7c1b7490ed7e3cf5afc42ddf7ed32321291ae3e8c313214a074bb171117a3b
  docker.io/lycheeverse/lychee:0.7.1@sha256:ff7c1b7490ed7e3cf5afc42ddf7ed32321291ae3e8c313214a074bb171117a3b: 
  Pulling from lycheeverse/lychee
  a330b6cecb98: Pulling fs layer
  40a0245be6dc: Pulling fs layer
  455571742799: Pulling fs layer
```

But then (and maybe I misunderstand this) GitHub is running a new container for each instruction in the Dockerfile:

```console
  Step 2/12 : LABEL maintainer="Matthias Endler <matthias-endler@gmx.net>"
   ---> Running in bd4b79e0ea4c
  Removing intermediate container bd4b79e0ea4c
   ---> 4c8d000f406e
  Step 3/12 : LABEL repository="https://github.com/lycheeverse/lychee-action"
   ---> Running in 5693ae0d3a1a
  Removing intermediate container 5693ae0d3a1a
   ---> a0470fb08afa
  Step 4/12 : LABEL homepage="https://github.com/lycheeverse/lychee-action"
   ---> Running in a4438f1b0327
  Removing intermediate container a4438f1b0327
   ---> a9d5ee4e142f
  Step 5/12 : LABEL com.github.actions.name="Link Checker"
   ---> Running in 17447d43370a
  Removing intermediate container 17447d43370a
   ---> f82cba5035cb
  Step 6/12 : LABEL com.github.actions.description="Quickly check links in Markdown, HTML, and text files"
   ---> Running in f3a07dc7782b
  Removing intermediate container f3a07dc7782b
   ---> d37542ba4401
  Step 7/12 : LABEL com.github.actions.icon="external-link"
   ---> Running in 1d7ed59f7eaa
  Removing intermediate container 1d7ed59f7eaa
   ---> ea74aaf6e140
  Step 8/12 : LABEL com.github.actions.color="purple"
   ---> Running in 4c0c08724849
  Removing intermediate container 4c0c08724849
   ---> 75d84c6cc6c7
  Step 9/12 : COPY README.md /
   ---> ba10efdead6e
  Step 10/12 : COPY LICENSE-MIT LICENSE-APACHE /
   ---> 47c967a514d1
  Step 11/12 : COPY entrypoint.sh /entrypoint.sh
   ---> eb6c41209b6d
  Step 12/12 : ENTRYPOINT ["/entrypoint.sh"]
   ---> Running in 58e561523ac6
  Removing intermediate container 58e561523ac6
   ---> 95aa5c38f9d6
```

**Comment by wolf99** [comment]
I immediately don't see a good alternative for binaries however, I will need to do some research!

**Comment by mre** [comment]
I think intermediate containers are normal.

> Every command, in the Dockerfile, that could potentially alter the state of the image (such as RUN, since Docker cannot know if our command has side effects) produces an "intermediate image". That is, every time such a step is encountered an image will be created that holds the state produced by all the previous commands.

https://blog.hipolabs.com/understanding-docker-without-losing-your-shit-cf2b30307c63

Guess I'd get the same output locally.

That said, I think there should be a way to not build the Docker image at all and only used a cached version.

**Comment by mre** [comment]
Idea on how to use the Github Actions cache with Buildkit (end of the document):
https://github.com/docker/build-push-action/blob/master/docs/advanced/cache.md

**Comment by mre** [comment]
Looks like this can be closed.

**Comment by wolf99** [comment]
Believe it or not I haven't forgotten about this  😄 .

I'm still not sure how to continue though.

Is the question on a binary due to Lychee being implemented in Rust, and Rust being a compiled language, and composite Actions seem to really be fit for interpreted scripts (such as Python, JS, Bash, etc) ?

**Comment by mre** [comment]
Not sure I understand. Which question are you referring to?

You can't run raw binaries as Github actions from what I can tell and the intermediate Docker layers are normal. Building the Docker image is already pretty fast so I don't know what we should change here. 🤔

**Comment by wolf99** [comment]
Sorry, I'm being really basic here; Im trying to understand why there is a question about a binary?

I think (but am not sure) it is because:

1. Lychee itself releases as a binary and so this Action uses a Docker file that uses that binary
2. Lychee is released as a binary because it is implemented in Rust which is a compiled language
3. Compiling a program in a composite action is expected to be slower than using the binary in a Docker action

Do I understand correctly?

I'm not saying your conclusion is wrong, I'm just trying to understand more about Lychee, the Lychee Action and Actions in general 🙂

**Comment by mre** [comment]
Your three points are correct.
