### ISSUE TITLE
URL exclusion lists

### ISSUE THREAD

**Issue by dend** [lycheeverse/lychee-action#53]
I'm successfully leveraging the action for my blog, however I've noticed that some URLs are being caught accidentally (e.g., XML schema pointers) and I'd like to exclude them. Is there an out-of-the-box way to configure a URL exclusion list without fiddling with custom arguments?

**Comment by dend** [comment]
Thanks @mre - this did the trick! 🎉

For the schemas, they are Microsoft-specific, so not sure how relevant they would be to the broader community. Examples include:

```
http://schemas.zune.net/profiles/2008/01
https://schemas.microsoft.com/winfx/2006/xaml
https://schemas.microsoft.com/expression/blend/2008
http://schemas.openxmlformats.org/markup-compatibility/2006
https://schemas.microsoft.com/winfx/2006/xaml/presentation
```
What do you think?

**Comment by dend** [comment]
And on a totally unrelated note, I am happy to contribute with some documentation for the action (re: link exclusion) to make it easier for folks to solve the same issue I ahd.

**Comment by mre** [comment]
Looking at the URLs and doing some research, I think that we could exclude all URLs starting with https://schemas.microsoft.com and https://schemas.zune.net. For that we'll have to slightly change the code for false positives. I'll create a PR for that and will mention you there for review. 

As for the documentation, contributions would be very welcome, yes. 👍
