### ISSUE TITLE
Check gist and user profile links using GitHub tokens

### ISSUE THREAD

**Issue by JAremko** [lycheeverse/lychee-action#54]
We have a lot of gist links so CI constantly hits `429 Too Many Requests`  on them. 

Doing the same for GH profile links would also help.

- - - - - -

###### Thanks for the action. It's much better than what we used before :wink:

**Comment by mre** [comment]
Thanks for the report and the kind words. 😊 The missing piece to avoid 429's is rate limiting. We're collecting ideas in https://github.com/lycheeverse/lychee/issues/367.

**Comment by mre** [comment]
Closing this in favor of lycheeverse/lychee#367 to keep the lychee issues close to the code. All information should be over there.
