### ISSUE TITLE
Exit Code 2 is not causing the Action to fail

### ISSUE THREAD

**Issue by Stargator** [lycheeverse/lychee-action#58]
[We are in the process of setting up an Action to check our links](https://github.com/exercism/dart/pull/360/checks), but the link checker catches an error due to a bad link, but the Action is still passing even though the link checker returns an exit code of 2.

How are we suppose to get the Action to fail? We don't want any issues to be created since any bad links should be caught in PRs before they are merged.

**Comment by mre** [comment]
Hey @Stargator, can you try the config in https://github.com/lycheeverse/lychee-action/issues/20?
It's a common request, so we could add that to the `README.md`.

**Comment by Stargator** [comment]
@mre Thanks, I'll try it out.

**Comment by mre** [comment]
If you find that it works, please let us know. Also, pull requests for adding that section to the `README.md` are very welcome.

**Comment by mre** [comment]
Any luck?

**Comment by Stargator** [comment]
Some adjustment, but it works. I'll get a PR ready to update the documentation.

**Comment by mre** [comment]
Thanks!

**Comment by mre** [comment]
Closing this. In case you got a PR cooking I'd be glad to merge it. Thanks again for the feedback.
