### ISSUE TITLE
Issue not created

### ISSUE THREAD

**Issue by kaihendry** [lycheeverse/lychee-action#7]
What am I missing here?

![image](https://user-images.githubusercontent.com/765871/106246800-a5479a80-6249-11eb-9bcc-992e8e225609.png)

* https://github.com/kaihendry/sgunited-guides/issues
* https://github.com/kaihendry/sgunited-guides/runs/1789949370?check_suite_focus=true

**Comment by mre** [comment]
This is related to #1 and should be fixed with https://github.com/lycheeverse/lychee-action/commit/5abbdadaddae26c045f74832c946901b30d8566f now.
Can you try again? Sorry for the delay.

**Comment by mre** [comment]
Should be resolved. Feel free to reopen if that's not the case.
