### ISSUE TITLE
Bump to lychee 0.8.2

### ISSUE THREAD

**Issue by dkarlovi** [lycheeverse/lychee-action#72]
I'd create a PR, but not sure which Docker tag corresponds to which version, TBH.

**Comment by mre** [comment]
The Github pipeline recently got rewritten by @fauust and we need to add back version tags.
If you'd like to help out, here's the issue that needs to be fixed: https://github.com/lycheeverse/lychee/issues/417.

**Comment by mre** [comment]
This is done in `master` and `v1.13` now.
