### ISSUE TITLE
How to use `--exclude-file` to exclude all files in a folder?

### ISSUE THREAD

**Issue by choldgraf** [lycheeverse/lychee-action#76]
### Description

I'm trying to use the action and cannot figure out how to exclude a folder from my link checks. I've tried a number of things, but all of these either result in a `is a folder` error (presumably looking for a file), or a `file doesn't exist` error. Here's what I have tried:

- `--exclude-file 'myfolder/**/*.html'`
- `--exclude-file myfolder/**/*.html`
- `--exclude-file '^.*myfolder.*$'

I know this isn't super helpful, but this PR is where I've tried a bunch of different things to get this working (look for the commits with `lychee` in them: https://github.com/executablebooks/sphinx-book-theme/pull/487)

Any ideas what I might be doing wrong? Is there a documentation place where usage of `exclude-files` is documented with example usage?

**Comment by mre** [comment]
Yeah it's an open discussion. 
`--exclude-file` was a misnomer and will be deprecated. It doesn't mean "exclude these files" it means "here is a file with exclude patterns for URLs". So a file with something like "http://example.com/*" in it. Here's the `--help` message:

```
--exclude-file <exclude-file>...
File or files that contain URLs to be excluded from checking. Regular
expressions supported; one pattern per line. Automatically excludes
patterns from `.lycheeignore` if file exists
```

There is currently no way to exclude paths other than using complicated glob patterns. 
I'd like to get your input on the suggestion over here: https://github.com/lycheeverse/lychee/issues/418#issuecomment-1031413713. It's pretty easy to implement, but we need more eyeballs to get the design right this time.

**Comment by mre** [comment]
Version 1.5.0 with lychee v0.10.0 was just released. You can now use `--exclude-path path/to/myfolder`. ☺️ Feel free to reopen in case of issues.
