### ISSUE TITLE
cat: /tmp/lychee/out.md: No such file or directory

### ISSUE THREAD

**Issue by vipulgupta2048** [lycheeverse/lychee-action#82]
Hey @mre I think our fix with #77 didn't work out. I made a PR to upgrade the action manually, dependabot didn't update it automatically for some reason and here's the output I got. Nothing urgent with this, but following up and seeing if we indeed did fix the root cause for this. 

https://github.com/balena-io/docs/runs/5361916108?check_suite_focus=true

**Comment by mre** [comment]
It did work, but in this case it doesn't help because lychee panics. 😆 
It's because of a known bug in reqwest [here](https://github.com/seanmonstar/reqwest/pull/1399).
If lychee panics it doesn't create the output file (`/tmp/lychee/out.md` by default) and then the `cat` fails.

Couple things we can do:

* We should add a check if the file exists before `cat`.
* Even then lychee will still panic, so you might need to exclude that URL for now. 😞 
* I am considering to use a fork of reqwest until the bug is fixed upstream.

**Comment by mre** [comment]
I attempted to add a check for the missing output file in #83.

**Comment by mre** [comment]
A fix got merged and will be released as v1.3.2 after `master` turns green.

**Comment by mre** [comment]
v1.3.2 is out. 🎉 Thanks for reporting @vipulgupta2048. Let us know if it doesn't work for you.

**Comment by vipulgupta2048** [comment]
> so you might need to exclude that URL for now.

I see which URL it's failing on and i think it's right to panic on that URL. 

```
thread 'main' panicked at 'Cannot send request: SendError(Ok(Request { uri: Uri { url: Url { scheme: "https", cannot_be_a_base: false, username: "", password: None, host: Some(Domain("github.com")), port: None, path: "/shaunmulligan/hello-python-edison", query: None, fragment: None } }, source: FsPath("pages/learn/develop/hardware/gpio.md"), element: Some("a"), attribute: Some("href") }))', lychee-bin/src/commands/check.rs:85:14
```

I think it's time for me to finally solve this https://github.com/balena-io/docs/issues/2162, the template engine markdown is missing links by the wayside. So why now.

**Comment by vipulgupta2048** [comment]
I am learning some rust in my downtime. Can't we skip the URL that doesn't conform to the URI so that the thread doesn't panic and fail? 

https://github.com/balena-io/docs/runs/5391339647?check_suite_focus=true
Because it's panicking and handling at the moment. Just fine, but I wonder if we could handle the panic, skip this URL and move on to other URL's. 

Maybe the report can have a section for invalid URL's found?

**Comment by mre** [comment]
You're right. Even if the URI is invalid, the panic itself should **never** happen. I was hoping that [the PR](https://github.com/seanmonstar/reqwest/pull/1399) for reqwest would be merged quickly (and it would benefit the entire Rust ecosystem), but I don't see any progress right now. 😞 

From what I can see, reqwest simply does a `url.as_str().parse()`. We should add that line before calling into reqwest while we wait for the upstream crate to fix it for good. (It might be a nice PR to get started... 😉)
We would unnecessarily parse the URL twice (once on our side and once on theirs), but it's definitely better than panicking.

**Comment by vipulgupta2048** [comment]
Roger that, I will take a swing at this. Appreciate the context.
