### ISSUE TITLE
README example has wrong `if` condition 

### ISSUE THREAD

**Issue by pat-s** [lycheeverse/lychee-action#94]
Which does not trigger issue creation for failing links.

```
if: ${{ steps.lychee.outputs.exit_code != 0 }}
```

should be 

```
if: ${{ steps.lychee.outputs.exit_code }} != 0
```

**Comment by mre** [comment]
Hey @pat-s,

I saw some cases where the current syntax was suggested:
* https://docs.github.com/en/actions/learn-github-actions/expressions#example-for-composite-action-step
* https://timheuer.com/blog/manually-force-a-failure-in-github-action-step/#evaluating-your-condition-and-failing-the-step-manually

Perhaps both work?
Although I think you ran into issues with the existing syntax, right?

Actually maybe even removing the `${{` and `}}` would work.
https://docs.github.com/en/actions/using-jobs/using-conditions-to-control-job-execution
It seems to be a special case for conditions.

**Comment by mre** [comment]
Cool, I've merged the PR. We should also test the version without the curly braces at some point.
Thanks a lot for the fix @pat-s.
