### ISSUE TITLE
Failed: Network error when trying to connect to an endpoint via hubcaps on valid links

### ISSUE THREAD

**Issue by Rizwan-Hasan** [lycheeverse/lychee-action#97]
Currently using the latest lychee action 1.4.0 and shows `Failed: Network error when trying to connect to an endpoint via hubcaps` on valid github links

**Comment by mre** [comment]
Sorry,

due to a race condition in the pipeline, we pushed an older version of lychee (0.8.2) to the 0.9.0 tag.
The new release binaries didn't exist yet, causing the binary to use old ones. 
This is fixed now and the image got pushed again. Update the image sha accordingly.

Can you try again by using v1.4.1?

**Comment by Rizwan-Hasan** [comment]
It's okay!
Just run the action using 1.4.1 and there are so many 429 errors with GitHub links.

Now working:
✗ [429] https://github.com/allegroai/trains/blob/master/docs/trains.conf#L3 | Network error: Too Many Requests
✗ [429] https://github.com/allegroai/trains/issues/239 | Network error: Too Many Requests

Working:
✔ [200] https://github.com/allegroai/clearml/tree/master/examples
✔ [200] https://github.com/allegroai/clearml/tree/master/examples/frameworks/ignite

**Comment by mre** [comment]
Okay checking your pipeline again I can see that you're testing a lot of Github links and you run into the rate limiting (even though you set a token; [the limit is 1000 requests/hour](https://docs.github.com/en/rest/overview/resources-in-the-rest-api#requests-from-github-actions)).
You can try to exclude some Github links with `--exclude github.com/allegroai/clearml/whatever` and reduce the concurrency with `--max-concurrency 5` or so (default is 128).
There is no way to delay requests. Instead, we plan to have per-site request limiting with https://github.com/lycheeverse/lychee/issues/36 in the future.

**Comment by mre** [comment]
You could also split up the run into two invocations of lychee and add a sleep in-between, but I would only try that if the above doesn't help.

**Comment by Rizwan-Hasan** [comment]
Thanks a lot.
